#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features='run_py_script',
        source='calc_siab_moments.py',
        #deps=[ctx.path_to(ctx, 'SIAB_PATH', 'siab_recoded.pickle')],
        target=[ctx.path_to(ctx, 'OUT_DATA', 'siab_ols_wage_male.csv'),
                ctx.path_to(ctx, 'OUT_DATA', 'siab_ols_wage_female.csv'),
                ctx.path_to(ctx, 'OUT_DATA', 'siab_ft.csv'),
                ctx.path_to(ctx, 'OUT_DATA', 'siab_pt.csv'),
                ctx.path_to(ctx, 'OUT_DATA', 'siab_inact.csv'),
                ctx.path_to(ctx, 'OUT_DATA', 'siab_experience.csv'),
                ],
    )