#! python


def build(ctx):

    # Illustrate simple use of run_py_script    
    ctx(
        features='run_py_script',
        source='calc_siab_moments.py',
        # deps=[ctx.path_to(ctx, 'SIAB_PATH', 'siab_recoded.pickle')],
        # target=ctx.path_to(ctx, 'OUT_DATA', 'siab_recoded.pickle'),
    )