---
version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-latest
conda:
  environment: docs/rtd_environment.yml
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
