---
codecov:
  notify:
    require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  range: 50...100
ignore:
  - setup.py
  - dashboard/
  - src/_gettsim/parameters/_dynamic_pension_data/
  - src/_gettsim_tests/
