codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

ignore:
  - "setup.py"
  - "dashboard/**/*"
  - "gettsim/tests"
  - "gettsim/parameters/_dynamic_pension_data"
  - "gettsim/aggregation_jax.py"
