{% set data = load_setup_py_data() %}

package:
  name: gettsim
  version: {{ data.get('version') }}

source:
  path: ../gettsim

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - pandas
    - pytest
    - pyyaml

test:
  commands:
    - pytest
  files:
    - gettsim/tests/
  requires:
    - pytest
    - pytest-cov
    - pytest-xdist
  imports:
    - gettsim

about:
  home: https://github.com/iza-institute-of-labor-economics/gettsim
  license: AGPLv3
  license_file: LICENSE
  summary: German tax and transfer simulator.
