"""Import all functions to a central place in order to automatically create the overview
in the documentation."""

from _gettsim.demographic_vars import *
from _gettsim.taxes.abgeltungssteuer.abgeltungssteuer import *
from _gettsim.taxes.einkommensgrenzen.einkommensgrenzen import *
from _gettsim.taxes.einkommensteuer.einkommen.einkünfte import *
from _gettsim.taxes.einkommensteuer.einkommen.vorsorgeaufwand import *
from _gettsim.taxes.einkommensteuer.einkommen.zu_versteuerndes_einkommen import *
from _gettsim.taxes.einkommensteuer.einkommensteuer import *
from _gettsim.taxes.einkommensteuer.freibetraege.alleinerziehend import *
from _gettsim.taxes.einkommensteuer.freibetraege.altersfreibetrag import *
from _gettsim.taxes.einkommensteuer.freibetraege.freibetraege import *
from _gettsim.taxes.einkommensteuer.freibetraege.kinderfreibetrag import *
from _gettsim.taxes.einkommensteuer.freibetraege.pauschbetrag_behinderung import *
from _gettsim.taxes.einkommensteuer.freibetraege.sonderausgaben import *
from _gettsim.taxes.einkommensteuer.solidaritaetszuschlag import *
from _gettsim.taxes.lohnsteuer.einkommen import *
from _gettsim.taxes.lohnsteuer.lohnsteuer import *
from _gettsim.taxes.sozialversicherungsbeitraege.arbeitslosenversicherung.arbeitslosenversicherung import *
from _gettsim.taxes.sozialversicherungsbeitraege.krankenversicherung.beitragssatz import *
from _gettsim.taxes.sozialversicherungsbeitraege.krankenversicherung.einkommen import *
from _gettsim.taxes.sozialversicherungsbeitraege.krankenversicherung.krankenversicherung import *
from _gettsim.taxes.sozialversicherungsbeitraege.pflegeversicherung.beitragssatz import *
from _gettsim.taxes.sozialversicherungsbeitraege.pflegeversicherung.pflegeversicherung import *
from _gettsim.taxes.sozialversicherungsbeitraege.rentenversicherung.rentenversicherung import *
from _gettsim.taxes.sozialversicherungsbeitraege.sozialversicherungsbeitraege import *
from _gettsim.transfers.arbeitslosengeld.arbeitslosengeld import *
from _gettsim.transfers.arbeitslosengeld_2.arbeitslosengeld_2 import *
from _gettsim.transfers.arbeitslosengeld_2.einkommen import *
from _gettsim.transfers.arbeitslosengeld_2.kindergelduebertrag import *
from _gettsim.transfers.arbeitslosengeld_2.regelbedarf import *
from _gettsim.transfers.arbeitslosengeld_2.vermoegen import *
from _gettsim.transfers.elterngeld.einkommen import *
from _gettsim.transfers.elterngeld.elterngeld import *
from _gettsim.transfers.elterngeld.geschwisterbonus import *
from _gettsim.transfers.erziehungsgeld.erziehungsgeld import *
from _gettsim.transfers.grundsicherung.im_alter import *
from _gettsim.transfers.grundsicherung.im_alter.einkommen import *
from _gettsim.transfers.grundsicherung.im_alter.im_alter import *
from _gettsim.transfers.kinderbonus.kinderbonus import *
from _gettsim.transfers.kindergeld.kindergeld import *
from _gettsim.transfers.kinderzuschlag.einkommen import *
from _gettsim.transfers.kinderzuschlag.kinderzuschlag import *
from _gettsim.transfers.kinderzuschlag.regelbedarf import *
from _gettsim.transfers.rente.altersrente.altersgrenzen import *
from _gettsim.transfers.rente.altersrente.altersrente import *
from _gettsim.transfers.rente.altersrente.besonders_langjährig.besonders_langjährig import *
from _gettsim.transfers.rente.altersrente.für_frauen.für_frauen import *
from _gettsim.transfers.rente.altersrente.langjährig.langjährig import *
from _gettsim.transfers.rente.altersrente.wartezeit import *
from _gettsim.transfers.rente.altersrente.wegen_arbeitslosigkeit.wegen_arbeitslosigkeit import *
from _gettsim.transfers.rente.erwerbsminderung.erwerbsminderung import *
from _gettsim.transfers.rente.grundrente.grundrente import *
from _gettsim.transfers.rente.rente import *
from _gettsim.transfers.unterhalt.unterhalt import *
from _gettsim.transfers.unterhaltsvorschuss.unterhaltsvorschuss import *
from _gettsim.transfers.vorrangpruefungen.vorrangpruefungen import *
from _gettsim.transfers.wohngeld.einkommen import *
from _gettsim.transfers.wohngeld.miete import *
from _gettsim.transfers.wohngeld.voraussetzungen import *
from _gettsim.transfers.wohngeld.wohngeld import *
