import pandas as pd

from gettsim.benefits.arbeitsl_geld_2 import alg2
from gettsim.pre_processing.apply_tax_funcs import apply_tax_transfer_func


def sum_basis_arbeitsl_geld_2_eink(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):
    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["sum_basis_arbeitsl_geld_2_eink"]


def sum_arbeitsl_geld_2_eink(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):

    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["sum_arbeitsl_geld_2_eink"]


def arbeitsl_geld_2_brutto_eink_hh(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):
    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["arbeitsl_geld_2_brutto_eink_hh"]


def alleinerziehenden_mehrbedarf(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):
    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["alleinerziehenden_mehrbedarf"]


def regelbedarf_m(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):
    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["regelbedarf_m"]


def regelsatz_m(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):
    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["regelsatz_m"]


def kost_unterk_m(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):
    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["kost_unterk_m"]


def unterhaltsvors_m_hh(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):
    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["unterhaltsvors_m_hh"]


def eink_anrechn_frei(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):
    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["eink_anrechn_frei"]


def arbeitsl_geld_2_eink(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):
    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["arbeitsl_geld_2_eink"]


def sum_arbeitsl_geld_2_eink_hh(
    p_id,
    hh_id,
    tu_id,
    vorstand_tu,
    kind,
    alter,
    kaltmiete_m,
    heizkost_m,
    wohnfläche,
    bewohnt_eigentum,
    alleinerziehend,
    bruttolohn_m,
    ges_rente_m,
    kapital_eink_m,
    arbeitsl_geld_m,
    sonstig_eink_m,
    eink_selbstst_m,
    vermiet_eink_m,
    eink_st_m,
    soli_st_m,
    sozialv_beit_m,
    kindergeld_m_hh,
    unterhaltsvors_m,
    elterngeld_m,
    jahr,
    arbeitsl_geld_2_params,
):
    df = pd.concat(
        [
            p_id,
            hh_id,
            tu_id,
            vorstand_tu,
            kind,
            alter,
            kaltmiete_m,
            heizkost_m,
            wohnfläche,
            bewohnt_eigentum,
            alleinerziehend,
            bruttolohn_m,
            ges_rente_m,
            kapital_eink_m,
            arbeitsl_geld_m,
            sonstig_eink_m,
            eink_selbstst_m,
            vermiet_eink_m,
            eink_st_m,
            soli_st_m,
            sozialv_beit_m,
            kindergeld_m_hh,
            unterhaltsvors_m,
            elterngeld_m,
            jahr,
        ],
        axis=1,
    )

    in_cols = [
        "p_id",
        "hh_id",
        "tu_id",
        "vorstand_tu",
        "kind",
        "alter",
        "kaltmiete_m",
        "heizkost_m",
        "wohnfläche",
        "bewohnt_eigentum",
        "alleinerziehend",
        "bruttolohn_m",
        "ges_rente_m",
        "kapital_eink_m",
        "arbeitsl_geld_m",
        "sonstig_eink_m",
        "eink_selbstst_m",
        "vermiet_eink_m",
        "eink_st_m",
        "soli_st_m",
        "sozialv_beit_m",
        "kindergeld_m_hh",
        "unterhaltsvors_m",
        "elterngeld_m",
        "jahr",
    ]

    out_cols = [
        "sum_basis_arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink",
        "arbeitsl_geld_2_brutto_eink_hh",
        "alleinerziehenden_mehrbedarf",
        "regelbedarf_m",
        "regelsatz_m",
        "kost_unterk_m",
        "unterhaltsvors_m_hh",
        "eink_anrechn_frei",
        "arbeitsl_geld_2_eink",
        "sum_arbeitsl_geld_2_eink_hh",
    ]

    df = apply_tax_transfer_func(
        df,
        tax_func=alg2,
        level=["hh_id"],
        in_cols=in_cols,
        out_cols=out_cols,
        func_kwargs={"params": arbeitsl_geld_2_params},
    )

    return df["sum_arbeitsl_geld_2_eink_hh"]
